# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Daily SRC Notices

on:
#  schedule:
#    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Running get_src_notices
      run: |
        python get_src_notices.py > output/`date +%Y%m%d`.txt

    - name: Create local changes
      run: |
        git add output/`date +%Y%m%d`.txt

    - name: commit
      run: |
        git config --global user.email root@ohlinge.cn
        git config --global user.name 1in9e
        git commit -m "update" -a --allow-empty

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
